### ISSUE TITLE
v2ray-geodata 中geoip  geosite 可否改为 Loyalsoldier/v2ray-rules-dat地址？

### ISSUE THREAD

**Issue by swxk521** [xiaorouji/openwrt-passwall-packages#101]
### 描述你想要的新功能

流媒体等有的不仅需要域名还需要代理IP，比如netflix，原数据不带这些分类。
但是passwall2中默认的更新是Loyalsoldier/v2ray-rules-dat地址。

**Comment by smallprogram** [comment]
PS1中默认就是Loyalsoldier/v2ray-rules-dat,无需修改
https://github.com/xiaorouji/openwrt-passwall/blob/6d9c4dc4c722198a52fb51475de903b256ef1008/luci-app-passwall/root/usr/share/passwall/rule_update.lua#L33-L34

**Comment by swxk521** [comment]
> PS1中默认就是Loyalsoldier/v2ray-rules-dat,无需修改 https://github.com/xiaorouji/openwrt-passwall/blob/6d9c4dc4c722198a52fb51475de903b256ef1008/luci-app-passwall/root/usr/share/passwall/rule_update.lua#L33-L34

不好意思，没表达清楚，是编译时的源数据
https://github.com/xiaorouji/openwrt-passwall-packages/blob/main/v2ray-geodata/Makefile
当然也可以变，只是提个建议。

**Comment by smallprogram** [comment]
> > PS1中默认就是Loyalsoldier/v2ray-rules-dat,无需修改 https://github.com/xiaorouji/openwrt-passwall/blob/6d9c4dc4c722198a52fb51475de903b256ef1008/luci-app-passwall/root/usr/share/passwall/rule_update.lua#L33-L34
> 
> 不好意思，没表达清楚，是编译时的源数据 https://github.com/xiaorouji/openwrt-passwall-packages/blob/main/v2ray-geodata/Makefile 当然也可以不改，只是提个建议。

好滴
