### ISSUE TITLE
[Bug]: 最新版4.72-1订阅不了hy1和hy2

### ISSUE THREAD

**Issue by luowei729** [xiaorouji/openwrt-passwall-packages#102]
### 描述您遇到的bug

[Bug]: 最新版4.72-1订阅不了hy1和hy2

### 复现此Bug的步骤

[Bug]: 最新版4.72-1订阅不了hy1和hy2

### 您想要实现的目的

[Bug]: 最新版4.72-1订阅不了hy1和hy2

### 日志信息

![image](https://github.com/xiaorouji/openwrt-passwall-packages/assets/10611605/f52b0bde-9fb9-4683-bdb5-4a58538affd5)
上面是hy2无法订阅

然后hy1节点passwall无法启动，报错
 [31mFATAL [0m[0000] create service: parse outbound[0]: invalid up speed format: 300 Mbps: unhandled size name: mbps

### 截图

![image](https://github.com/xiaorouji/openwrt-passwall-packages/assets/10611605/4fad9b6d-629b-4d76-8f24-1f0db5a37af0)

### 系统相关信息

4.72-1

**Comment by luowei729** [comment]
CLW  CLA  小火箭  三平台软件订阅正常

**Comment by bi4tms** [comment]
作者更新完了就不管了，@了也不回应一下

**Comment by smallprogram** [comment]
> 作者更新完了就不管了，@了也不回应一下

不是，老铁，这是个开源项目 ，又不是商业项目，作者也没有义务去满足各种需求，就不行自己研究研究提个PR啥的。你技术不行不会，直接拿来主义，那就算了，还在这说什么风凉话呢。
你这话说的我咋这不爱听呢。`什么叫更新完就不管了，@也不回应。`, 人家凭什么就需要管，凭什么@了就必须回复你呢。麻烦你矫正一下思想好不好。没事多研究研究，提提PR啥的，不要做伸手党，一个开源项目需要的是大家一起去维护，去完善，而不是某几个人或者某个人的责任。好吧。

**Comment by bi4tms** [comment]
> > 作者更新完了就不管了，@了也不回应一下
> 
> 不是，老铁，这是个开源项目 ，又不是商业项目，作者也没有义务去满足各种需求，就不行自己研究研究提个PR啥的。你技术不行不会，直接拿来主义，那就算了，还在这说什么风凉话呢。 你这话说的我咋这不爱听呢。`什么叫更新完就不管了，@也不回应。`, 人家凭什么就需要管，凭什么@了就必须回复你呢。麻烦你矫正一下思想好不好。没事多研究研究，提提PR啥的，不要做伸手党，一个开源项目需要的是大家一起去维护，去完善，而不是某几个人或者某个人的责任。好吧。

这并不是什么风凉话，作者升级版本本身没有问题 ，但是起码要测试一下更新完能否正常使用吧，上一个版本是没有这个问题的，最新版本出现的bug我提出issue也过去整整3天了，作者如果短期没时间修可以回应一下，大家耐心等就行了，术业有专攻，不可能要求每个人都能写代码的。

**Comment by xiaorouji** [comment]
@luowei729 
Please provide a subscription link:
Email: xiaoroujixxoo@gmail.com

**Comment by luowei729** [comment]
> @luowei729 Please provide a subscription link: Email: [xiaoroujixxoo@gmail.com](mailto:xiaoroujixxoo@gmail.com)

订阅链接已发邮件，请查收
