### ISSUE TITLE
[Bug]: 拉取最新源码编译brook报错

### ISSUE THREAD

**Issue by bi4tms** [xiaorouji/openwrt-passwall-packages#105]
### 描述您遇到的bug

拉取最新源码编译报错，提示编译brook失败，具体日志如下：
make[3]: Entering directory '/home/x86.6.1/lede/feeds/passwall_packages/brook'
touch /home/x86.6.1/lede/build_dir/target-x86_64_musl/brook-20240214/.prepared_42676dc8da53f434f4d5a696c6dc84a7_6664517399ebbbc92a37c5bb081b5c53_check
. /home/x86.6.1/lede/include/shell.sh; /home/x86.6.1/lede/staging_dir/host/bin/libdeflate-gzip -dc /home/x86.6.1/lede/dl/brook-20240214.tar.gz | tar -C /home/x86.6.1/lede/build_dir/target-x86_64_musl/brook-20240214/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/x86.6.1/lede/build_dir/target-x86_64_musl/brook-20240214
Applying ./patches/0001-update-iploc-to-fix-build-for-riscv64.patch using plaintext: 
patching file go.mod
Hunk #1 FAILED at 8.
1 out of 1 hunk FAILED -- saving rejects to file go.mod.rej
patching file go.sum
Hunk #1 FAILED at 180.
1 out of 1 hunk FAILED -- saving rejects to file go.sum.rej
Patch failed!  Please fix ./patches/0001-update-iploc-to-fix-build-for-riscv64.patch!
make[3]: *** [Makefile:52: /home/x86.6.1/lede/build_dir/target-x86_64_musl/brook-20240214/.prepared_42676dc8da53f434f4d5a696c6dc84a7_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/x86.6.1/lede/feeds/passwall_packages/brook'
time: package/feeds/passwall_packages/brook/compile#0.21#0.11#0.36
    ERROR: package/feeds/passwall_packages/brook failed to build.
make[2]: *** [package/Makefile:116: package/feeds/passwall_packages/brook/compile] Error 1
make[2]: Leaving directory '/home/x86.6.1/lede'
make[1]: *** [package/Makefile:110: /home/x86.6.1/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/x86.6.1/lede'
make: *** [/home/x86.6.1/lede/include/toplevel.mk:231：world] 错误 2
如需至lean项目下提issue烦请告知
@smallprogram @xiaorouji 

### 复现此Bug的步骤

拉取最新源码编译

### 您想要实现的目的

顺利通过编译

### 日志信息

同上

### 系统相关信息

x86

**Comment by smallprogram** [comment]
再试一下
