### ISSUE TITLE
[Bug]: 6.1.72出错

### ISSUE THREAD

**Issue by qq1316237299** [xiaorouji/openwrt-passwall-packages#107]
### 描述您遇到的bug

6.1.72出错。

### 复现此Bug的步骤

6.1.72出错。

### 您想要实现的目的

6.1.72出错。

### 日志信息

make[3]: Leaving directory '/home/qq1316237299/lede/feeds/passwall_packages/dns2socks'
time: package/feeds/passwall_packages/dns2socks/compile#0.07#0.04#0.11
make[3]: Entering directory '/home/qq1316237299/lede/feeds/passwall_packages/dns2tcp'
mkdir -p /home/qq1316237299/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/qq1316237299/lede/tmp/.root-copy.flock -c 'cp -fpR /home/qq1316237299/lede/build_dir/target-x86_64_musl/dns2tcp-1.1.0/.pkgdir/dns2tcp/. /home/qq1316237299/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/qq1316237299/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.dns2tcp_installed
echo "dns2tcp" >> /home/qq1316237299/lede/staging_dir/target-x86_64_musl/pkginfo/dns2tcp.default.install
make[3]: Leaving directory '/home/qq1316237299/lede/feeds/passwall_packages/dns2tcp'
time: package/feeds/passwall_packages/dns2tcp/compile#0.10#0.02#0.12
make[3]: Entering directory '/home/qq1316237299/lede/feeds/passwall_packages/microsocks'
mkdir -p /home/qq1316237299/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/qq1316237299/lede/tmp/.root-copy.flock -c 'cp -fpR /home/qq1316237299/lede/build_dir/target-x86_64_musl/microsocks-1.0.3/.pkgdir/microsocks/. /home/qq1316237299/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/qq1316237299/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.microsocks_installed
echo "microsocks" >> /home/qq1316237299/lede/staging_dir/target-x86_64_musl/pkginfo/microsocks.default.install
make[3]: Leaving directory '/home/qq1316237299/lede/feeds/passwall_packages/microsocks'
time: package/feeds/passwall_packages/microsocks/compile#0.09#0.03#0.11
make[3]: Entering directory '/home/qq1316237299/lede/feeds/passwall_packages/tcping'
mkdir -p /home/qq1316237299/lede/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/qq1316237299/lede/tmp/.root-copy.flock -c 'cp -fpR /home/qq1316237299/lede/build_dir/target-x86_64_musl/tcping//tcping-0.3/.pkgdir/tcping/. /home/qq1316237299/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/qq1316237299/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.tcping_installed
echo "tcping" >> /home/qq1316237299/lede/staging_dir/target-x86_64_musl/pkginfo/tcping.default.install
make[3]: Leaving directory '/home/qq1316237299/lede/feeds/passwall_packages/tcping'
time: package/feeds/passwall_packages/tcping/compile#0.08#0.04#0.11
make[3]: Entering directory '/home/qq1316237299/lede/feeds/passwall_packages/brook'
touch /home/qq1316237299/lede/build_dir/target-x86_64_musl/brook-20240214/.prepared_3c6106f9752e335233f64cbebbf59946_6664517399ebbbc92a37c5bb081b5c53_check
. /home/qq1316237299/lede/include/shell.sh; /home/qq1316237299/lede/staging_dir/host/bin/libdeflate-gzip -dc /home/qq1316237299/lede/dl/brook-20240214.tar.gz | tar -C /home/qq1316237299/lede/build_dir/target-x86_64_musl/brook-20240214/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/qq1316237299/lede/build_dir/target-x86_64_musl/brook-20240214

Applying ./patches/0001-update-iploc-to-fix-build-for-riscv64.patch using plaintext:
patching file go.mod
Hunk https://github.com/coolsnowwolf/lede/issues/1 FAILED at 8.
1 out of 1 hunk FAILED -- saving rejects to file go.mod.rej
patching file go.sum
Hunk https://github.com/coolsnowwolf/lede/issues/1 FAILED at 180.
1 out of 1 hunk FAILED -- saving rejects to file go.sum.rej
Patch failed! Please fix ./patches/0001-update-iploc-to-fix-build-for-riscv64.patch!
Makefile:45: recipe for target '/home/qq1316237299/lede/build_dir/target-x86_64_musl/brook-20240214/.prepared_3c6106f9752e335233f64cbebbf59946_6664517399ebbbc92a37c5bb081b5c53' failed
make[3]: *** [/home/qq1316237299/lede/build_dir/target-x86_64_musl/brook-20240214/.prepared_3c6106f9752e335233f64cbebbf59946_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/qq1316237299/lede/feeds/passwall_packages/brook'
time: package/feeds/passwall_packages/brook/compile#0.08#0.04#0.10
ERROR: package/feeds/passwall_packages/brook failed to build.
package/Makefile:114: recipe for target 'package/feeds/passwall_packages/brook/compile' failed
make[2]: *** [package/feeds/passwall_packages/brook/compile] Error 1
make[2]: Leaving directory '/home/qq1316237299/lede'
package/Makefile:110: recipe for target '/home/qq1316237299/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/qq1316237299/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/qq1316237299/lede'
/home/qq1316237299/lede/include/toplevel.mk:229: recipe for target 'world' failed
make: *** [world] Error 2

### 截图

![QQ截图20240115035344](https://github.com/xiaorouji/openwrt-passwall-packages/assets/42686656/2cc0d9bf-c2de-4640-93a1-c396bb206de1)

### 系统相关信息

4.72-2

**Comment by qq1316237299** [comment]
x86

**Comment by smallprogram** [comment]
再试一下

**Comment by qq1316237299** [comment]
> 再试一下

好的

**Comment by qq1316237299** [comment]
> 再试一下


> 再试一下

编译完成，谢谢了
