### ISSUE TITLE
[Bug]: 编译lienol的openwrt 22.03分支，在hysteria编译部分报错

### ISSUE THREAD

**Issue by gforce1206** [xiaorouji/openwrt-passwall-packages#110]
### 描述您遇到的bug

`net/http/httputil
github.com/pelletier/go-toml/v2/internal/tracker
github.com/pelletier/go-toml/v2
github.com/spf13/viper/internal/encoding/toml
github.com/spf13/viper

make[3]: *** [Makefile:62: /home/lien/Desktop/openwrt/build_dir/target-aarch64_cortex-a53_musl/hysteria-app-v2.2.3/.built] Error 1
make[3]: Leaving directory '/home/lien/Desktop/openwrt/feeds/passwall_packages/hysteria'
time: package/feeds/passwall_packages/hysteria/compile#63.52#16.82#169.19
    ERROR: package/feeds/passwall_packages/hysteria failed to build.
make[2]: *** [package/Makefile:120: package/feeds/passwall_packages/hysteria/compile] Error 1
make[2]: Leaving directory '/home/lien/Desktop/openwrt'
make[1]: *** [package/Makefile:114: /home/lien/Desktop/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lien/Desktop/openwrt'
make: *** [/home/lien/Desktop/openwrt/include/toplevel.mk:230: world] Error 2`
Ubuntu20.04.6物理机编译

### 复现此Bug的步骤

无

### 您想要实现的目的

无

### 日志信息

无

### 系统相关信息

4.72-2

**Comment by Gzxhwq** [comment]
Go版本最低要求到1.21了，22.03已经不能满足，切换到23.05吧
