### ISSUE TITLE
[Bug]: 拉取最新源码编译gn报错

### ISSUE THREAD

**Issue by bi4tms** [xiaorouji/openwrt-passwall-packages#117]
### 描述您遇到的bug

  @@拉取最新源码编译gn报错
具体日志如下：
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:
git switch -c <new-branch-name>
Or undo this operation with:
git switch -
Turn off this advice by setting config variable advice.detachedHead to false
HEAD is now at a2e2717e Ensure read_file() files are considered by "gn analyze"
Packing checkout...
. /home/x86.6.6/lede/include/shell.sh; xzcat /home/x86.6.6/lede/dl/gn-2024-01-24-a2e2717e.tar.xz | tar -C /home/x86.6.6/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/* /home/x86.6.6/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e
touch /home/x86.6.6/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.preparedf54f9e38f05fc30b58b2dbb87be33533_6664517399ebbbc92a37c5bb081b5c53
python3 /home/x86.6.6/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/build/gen.py --no-last-commit-position
touch /home/x86.6.6/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.configured
MAKEFLAGS="" /home/x86.6.6/lede/staging_dir/host/bin/ninja  -j1 -C /home/x86.6.6/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/out
ninja: Entering directory `/home/x86.6.6/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/out'
[1/287] CXX src/base/command_line.o
FAILED: src/base/command_line.o 
clang++ -MMD -MF src/base/command_line.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++20 -Wrange-loop-analysis -Wextra-semi-stmt -c ../src/base/command_line.cc -o src/base/command_line.o
/bin/sh: 1: clang++: not found
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:58: /home/x86.6.6/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.built] Error 1
make[3]: Leaving directory '/home/x86.6.6/lede/feeds/passwall_packages/gn'
time: package/feeds/passwall_packages/gn/host-compile#7.12#0.74#13.72
    ERROR: package/feeds/passwall_packages/gn [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/passwall_packages/gn/host/compile] Error 1
make[2]: Leaving directory '/home/x86.6.6/lede'
make[1]: *** [package/Makefile:110: /home/x86.6.6/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/x86.6.6/lede'
make: *** [/home/x86.6.6/lede/include/toplevel.mk:231：world] 错误 2
@smallprogram @zxlhhyccc 

### 复现此Bug的步骤

常规编译

### 您想要实现的目的

修复bug

### 日志信息

同上

### 系统相关信息

最新

**Comment by smallprogram** [comment]
尝试编译一下，我这边没有问题

**Comment by smallprogram** [comment]
https://github.com/fw876/helloworld/issues/1385

**Comment by free-diy** [comment]
+1

**Comment by bi4tms** [comment]
> 这个其实很好解决，就是缺少了 /bin/sh: 1: clang++: not found 安装一下 apt install clang 再去编译一下试试

感谢，安装clang后可以编译通过

**Comment by jmmes** [comment]
> 这个其实很好解决，就是缺少了 /bin/sh: 1: clang++: not found 安装一下 apt install clang 再去编译一下试试

安装依赖了，还是报错，大佬帮忙看看哪里问题？
ninja: Entering directory `/home/user/openwrt/build_dir/hostpkg/gn-2024-01-24-a2e2717e/out'
[1/287] CXX src/base/command_line.o
FAILED: src/base/command_line.o 
g++ -MMD -MF src/base/command_line.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++20 -Wno-redundant-move -c ../src/base/command_line.cc -o src/base/command_line.o
g++: error: unrecognized command line option '-std=c++20'; did you mean '-std=c++2a'?
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:69: /home/user/openwrt/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.built] Error 1
make[3]: Leaving directory '/home/user/openwrt/feeds/PWpackages/gn'
time: package/feeds/PWpackages/gn/host-compile#0.06#0.06#0.11
    ERROR: package/feeds/PWpackages/gn [host] failed to build.
make[2]: *** [package/Makefile:126: package/feeds/PWpackages/gn/host/compile] Error 1
make[2]: Leaving directory '/home/user/openwrt'
make[1]: *** [package/Makefile:122: /home/user/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/user/openwrt'
make[1]: Leaving directory '/home/user/openwrt'
make: *** [/home/user/openwrt/include/toplevel.mk:232: world] Error 2
user@51929e3d59ad:~/openwrt$ clang -v
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

**Comment by dph5199278** [comment]
> > 这个其实很好解决，就是缺少了 /bin/sh: 1: clang++: not found 安装一下 apt install clang 再去编译一下试试
> 
> 安装依赖了，还是报错，大佬帮忙看看哪里问题？ ninja: Entering directory `/home/user/openwrt/build_dir/hostpkg/gn-2024-01-24-a2e2717e/out' [1/287] CXX src/base/command_line.o FAILED: src/base/command_line.o g++ -MMD -MF src/base/command_line.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++20 -Wno-redundant-move -c ../src/base/command_line.cc -o src/base/command_line.o g++: error: unrecognized command line option '-std=c++20'; did you mean '-std=c++2a'? ninja: build stopped: subcommand failed. make[3]: *** [Makefile:69: /home/user/openwrt/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.built] Error 1 make[3]: Leaving directory '/home/user/openwrt/feeds/PWpackages/gn' time: package/feeds/PWpackages/gn/host-compile#0.06#0.06#0.11 ERROR: package/feeds/PWpackages/gn [host] failed to build. make[2]: *** [package/Makefile:126: package/feeds/PWpackages/gn/host/compile] Error 1 make[2]: Leaving directory '/home/user/openwrt' make[1]: *** [package/Makefile:122: /home/user/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2 make[1]: *** Waiting for unfinished jobs.... make[2]: Leaving directory '/home/user/openwrt' make[1]: Leaving directory '/home/user/openwrt' make: *** [/home/user/openwrt/include/toplevel.mk:232: world] Error 2 user@51929e3d59ad:~/openwrt$ clang -v clang version 10.0.0-4ubuntu1 Target: x86_64-pc-linux-gnu Thread model: posix InstalledDir: /usr/bin Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9 Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9 Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9 Candidate multilib: .;@m64 Candidate multilib: 32;@m32 Candidate multilib: x32;@MX32 Selected multilib: .;@m64

你的gcc小于10，10以下不支持-std=c++20参数，需要改为-std=c++2a或者升级gcc到10以上版本。
