### ISSUE TITLE
[Bug]: shadowsocks-rust编译失败

### ISSUE THREAD

**Issue by qwerttvv** [xiaorouji/openwrt-passwall-packages#122]
### 描述您遇到的bug

两个机器，两个repo不同版本，都编译失败了
希望可以revert https://github.com/xiaorouji/openwrt-passwall-packages/commit/93ec4413b40b43ae68ea336ba07d84d7519f663c 
以前直接用bin无此问题

### 复现此Bug的步骤

编译shadowsocks-rust

### 您想要实现的目的

编译shadowsocks-rust

### 日志信息

日志在这里
https://github.com/qwerttvv/Router/actions/runs/7760138492/job/21165695572#step:12:292
https://github.com/qwerttvv/Router/actions/runs/7757582252/job/21157375899#step:12:342

### 系统相关信息

最新版
https://github.com/xiaorouji/openwrt-passwall-packages/tree/b68bd36087f3166bcc73e854b1123873931b25b3

**Comment by smallprogram** [comment]
https://github.com/sdf8057/ipq6000  问题可能出在你这个源码上，我用lean、openwrt23.05都没有问题
