### ISSUE TITLE
[Bug]: 拉取最新源码后报错

### ISSUE THREAD

**Issue by bi4tms** [xiaorouji/openwrt-passwall-packages#125]
### 描述您遇到的bug

拉取最新源码后编译报错，日志如下：
MAKEFLAGS="" /home/x86.5.10/lede/staging_dir/host/bin/ninja  -j1 -C /home/x86.5.10/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/out
ninja: Entering directory `/home/x86.5.10/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/out'
[1/287] CXX src/base/command_line.o
FAILED: src/base/command_line.o 
g++ -MMD -MF src/base/command_line.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++20 -Wno-redundant-move -c ../src/base/command_line.cc -o src/base/command_line.o
g++: error: unrecognized command line option '-std=c++20'; did you mean '-std=c++2a'?
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:58: /home/x86.5.10/lede/build_dir/hostpkg/gn-2024-01-24-a2e2717e/.built] Error 1
make[3]: Leaving directory '/home/x86.5.10/lede/feeds/passwall_packages/gn'
time: package/feeds/passwall_packages/gn/host-compile#0.38#0.14#0.53
    ERROR: package/feeds/passwall_packages/gn [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/passwall_packages/gn/host/compile] Error 1
make[2]: Leaving directory '/home/x86.5.10/lede'
make[1]: *** [package/Makefile:110: /home/x86.5.10/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/x86.5.10/lede'
make: *** [/home/x86.5.10/lede/include/toplevel.mk:231：world] 错误 2
@MoetaYuko @smallprogram 
应该最新的补丁问题，未更新前可以正常编译，编译环境为物理机Ubuntu22.04

### 复现此Bug的步骤

拉取最新源码编译

### 您想要实现的目的

修复bug

### 日志信息

同上

### 系统相关信息

x86

**Comment by MoetaYuko** [comment]
你的 gcc 版本是什么？openwrt 官方 sdk docker 镜像自带的 gcc10 支持 c++20，ubuntu 22.04 自带的 gcc11 更支持。你是不是自己装了老版本的 gcc？

**Comment by smallprogram** [comment]
```
g++: error: unrecognized command line option '-std=c++20'; did you mean '-std=c++2a'?
ninja: build stopped: subcommand failed.
```
这个错误，提示你的gcc编译器不识别-std=c++20这个编译选项，也就是说你的编译器不支持C++20标准，需要相对较新的编译器版本才支持。建议你升级一下编译器版本

**Comment by lxhao61** [comment]
问题一样，只是[报错不同](https://github.com/lxhao61/Actions-Original-OpenWrt/actions/runs/7884162525/job/21512565043)。

**Comment by hxlls** [comment]
可以试试更新gcc和G++版本
sudo apt update
安装GCC 10
sudo apt install gcc-10 g++-10
配置环境
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
查询下版本
gcc --version
g++ --version
一般正常来说会显示10.XX
这样应该就可以编译过了

**Comment by lxhao61** [comment]
gn就一个编译工具，不合理升级造成需要这样麻烦更新gcc和G++版本，无语。

**Comment by hxlls** [comment]
> gn就一个编译工具，不合理升级造成需要这样麻烦更新gcc和G++版本，无语。

这个是你安装工具的问题，实测就算是ubuntu22.04，如果用immo的那个一键脚本安装工具，大概率会安装9.X版本的，所以会造成出错，用immo的说的命令行安装环境，没这种问题

**Comment by MoetaYuko** [comment]
> gn就一个编译工具，不合理升级造成需要这样麻烦更新gcc和G++版本，无语。

祖宗之法不可变😁

**Comment by lxhao61** [comment]
> > gn就一个编译工具，不合理升级造成需要这样麻烦更新gcc和G++版本，无语。
> 
> 这个是你安装工具的问题，实测就算是ubuntu22.04，如果用immo的那个一键脚本安装工具，大概率会安装9.X版本的，所以会造成出错，用immo的说的命令行安装环境，没这种问题

用的 P3TERX 大 Actions-OpenWrt 云编译环境，之前一直无问题。

**Comment by lxhao61** [comment]
> > gn就一个编译工具，不合理升级造成需要这样麻烦更新gcc和G++版本，无语。
> 
> 祖宗之法不可变😁

随你高兴，现用 Immortal 大的 gn 替换解决问题。
