### ISSUE TITLE
[Bug]: 最新版lede源码编译passwall报错

### ISSUE THREAD

**Issue by Pacio** [xiaorouji/openwrt-passwall-packages#145]
### 描述您遇到的bug

github action过年前一直都正常编译固件， 放假回来试了几次都编译失败，报错只和passwall 相关

### 复现此Bug的步骤

设备:x86
编译环境:github action ubuntu22.04

### 您想要实现的目的

正常编译固件

### 日志信息

![image](https://github.com/xiaorouji/openwrt-passwall-packages/assets/6836705/a828f8fb-ec70-467b-862d-a67906ba54f4)
![image](https://github.com/xiaorouji/openwrt-passwall-packages/assets/6836705/969817e4-577e-4b01-8631-374095566e3c)

### 系统相关信息

最新版

**Comment by Gzxhwq** [comment]
提示需要开启CGO，但是应该没有需要CGO的选项？我这里编译是通过的。最近的更改是默认编译gvisor，但是gvisor应该也没要开启CGO

**Comment by Gzxhwq** [comment]
看到了，应该是go 1.22的问题，我看lean回退到1.21.5了

**Comment by swxk521** [comment]
xray编译不过了，等PR合并

**Comment by Gzxhwq** [comment]
Go 1.22开始，使用external linking的程序，无论程序本身有否调用到C语言的模块，也需要强制开启CGO了。

**Comment by Pacio** [comment]
> Go 1.22开始，使用external linking的程序，无论程序本身有否调用到C语言的模块，也需要强制开启CGO了。

那我这现在咋办？有什么临时解决办法吗

**Comment by Gzxhwq** [comment]
> > Go 1.22开始，使用external linking的程序，无论程序本身有否调用到C语言的模块，也需要强制开启CGO了。
> 
> 那我这现在咋办？有什么临时解决办法吗

lean已经回退go 1.21.5了，sing-box应该不会有问题。另外xray最新版要求go 1.22了，不过补丁暂时未合

**Comment by Pacio** [comment]
> > > Go 1.22开始，使用external linking的程序，无论程序本身有否调用到C语言的模块，也需要强制开启CGO了。
> > 
> > 
> > 那我这现在咋办？有什么临时解决办法吗
> 
> lean已经回退go 1.21.5了，sing-box应该不会有问题。另外xray最新版要求go 1.22了，不过补丁暂时未合

好的，我再试试，sing-box能用就够了

**Comment by Pacio** [comment]
问题解决，就是go 版本的问题

**Comment by jxph1123** [comment]
> 问题解决，就是go 版本的问题

怎么解决的
