### ISSUE TITLE
[Bug]: XARY 1.8.8 编译需要GOLANG 1.2.2 支持

### ISSUE THREAD

**Issue by iamyangyiok** [xiaorouji/openwrt-passwall-packages#146]
### 描述您遇到的bug

go: download go1.22: golang.org/toolchain@v0.0.1-go1.22.linux-amd64: Get "https://dl.google.com/go/v0.0.1-go1.22.linux-amd64.zip": dial tcp 120.232.233.161:443: connect: connection refused

make[3]: *** [Makefile:91: /home/yai/immortalwrt/build_dir/target-aarch64_cortex-a53_musl/Xray-core-1.8.8/.built] Error 1
make[3]: Leaving directory '/home/yai/immortalwrt/package/mypack/passwall-packages/xray-core'
time: package/mypack/passwall-packages/xray-core/compile#0.55#1.07#51.38
    ERROR: package/mypack/passwall-packages/xray-core failed to build.

### 复现此Bug的步骤

编译时

### 您想要实现的目的

能修复

### 日志信息

记录

### 系统相关信息

OPENWRT 21.02

**Comment by sbwml** [comment]
### 给你提供两个方案：

**方案一、在 `./scripts/feeds install -a` 操作之后替换 golang 为 1.22.x 版本**

```shell
rm -rf feeds/packages/lang/golang
git clone https://github.com/sbwml/packages_lang_golang -b 22.x feeds/packages/lang/golang
```

**方案二、Patch xray-core & xray-plugin 使其兼容 golang 1.21**

**具体参考：** https://github.com/sbwml/openwrt_helloworld/commits/go1.21

**xray-core：** https://github.com/sbwml/openwrt_helloworld/commit/71ba9a74dc44534df0b3586d7ad5df2d51ba873c
**xray-plugin：** https://github.com/sbwml/openwrt_helloworld/commit/0389f821fa29663392b2bdfb21b13930cc2efacf

**Comment by sbwml** [comment]
解决方法：https://github.com/xiaorouji/openwrt-passwall/discussions/2969

**Comment by yangxu52** [comment]
> 解决方法：[xiaorouji/openwrt-passwall#2969](https://github.com/xiaorouji/openwrt-passwall/discussions/2969)

如果同时编译sing-box和xray-core，是否有更优解？
目前sing-box在golang 1.21.x能编译通过，xray-core 1.8.7在golang 1.21.x也能通过，但是xray-core 1.8.8需要golang 1.22.x

**Comment by sbwml** [comment]
> > 解决方法：[xiaorouji/openwrt-passwall#2969](https://github.com/xiaorouji/openwrt-passwall/discussions/2969)
> 
> 如果同时编译sing-box和xray-core，是否有更优解？ 目前sing-box在golang 1.21.x能编译通过，xray-core 1.8.7在golang 1.21.x也能通过，但是xray-core 1.8.8需要golang 1.22.x

go1.22 可以编译xray-* 和 sing-box。甚至可以编译 go1.21 能编译的所有包

这里是用 go1.22 编译出来的包：https://opkg.cooluc.com/openwrt-23.05/aarch64_generic/

**Comment by yangxu52** [comment]
> > > 解决方法：[xiaorouji/openwrt-passwall#2969](https://github.com/xiaorouji/openwrt-passwall/discussions/2969)
> > 
> > 
> > 如果同时编译sing-box和xray-core，是否有更优解？ 目前sing-box在golang 1.21.x能编译通过，xray-core 1.8.7在golang 1.21.x也能通过，但是xray-core 1.8.8需要golang 1.22.x
> 
> go1.22 可以编译xray-* 和 sing-box。甚至可以编译 go1.21 能编译的所有包
> 
> 这里是用 go1.22 编译出来的包：https://opkg.cooluc.com/openwrt-23.05/aarch64_generic/

![image](https://github.com/xiaorouji/openwrt-passwall-packages/assets/64672399/0ff8205d-dccf-4dc7-b4ea-53581272b8b5)
我使用github action编译的固件，看到xray-core升级后，我将golang替换到了1.22.x
![image](https://github.com/xiaorouji/openwrt-passwall-packages/assets/64672399/58326668-1cb4-42a8-824e-8f5b8e24cdf2)
之前sing-box是能编译过的。

**Comment by sbwml** [comment]
> > > > 解决方法：[xiaorouji/openwrt-passwall#2969](https://github.com/xiaorouji/openwrt-passwall/discussions/2969)
> > > 
> > > 
> > > 如果同时编译sing-box和xray-core，是否有更优解？ 目前sing-box在golang 1.21.x能编译通过，xray-core 1.8.7在golang 1.21.x也能通过，但是xray-core 1.8.8需要golang 1.22.x
> > 
> > 
> > go1.22 可以编译xray-* 和 sing-box。甚至可以编译 go1.21 能编译的所有包
> > 这里是用 go1.22 编译出来的包：https://opkg.cooluc.com/openwrt-23.05/aarch64_generic/
> 我使用github action编译的固件，看到xray-core升级后，我将golang替换到了1.22.x ![image](https://private-user-images.githubusercontent.com/64672399/308083879-58326668-1cb4-42a8-824e-8f5b8e24cdf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjEyODgsIm5iZiI6MTcwOTAyMDk4OCwicGF0aCI6Ii82NDY3MjM5OS8zMDgwODM4NzktNTgzMjY2NjgtMWNiNC00MmE4LTgyNGUtOGY1YjhlMjRjZGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA4MDMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZDRiOGY0ODNmNDAzZjdiNTk1NzM1OWU4NGRlOTYzZDIzNGE1ZDFmY2FjYTgxYzc2NzZiMGJmYzc2ZGY1NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hzNNekUUJ8qzWE8baVjjB7xVNj1acp_dZQ2Kk5jj-IA) 之前sing-box是能编译过的。

是这里的 singbox 包问题，go1.22 要求 cgo。根据：https://github.com/golang/go/commit/079dfdcac0448168e22a72baa61b9ab5de8ce54e

解决方法两个：
1、使用这个 singbox 包 https://github.com/sbwml/openwrt_helloworld/tree/v5/sing-box

2、直接删除 https://github.com/xiaorouji/openwrt-passwall-packages/blob/main/sing-box/Makefile#L49 这行，或者把 `CGO_ENABLED=0` 改成 ` CGO_ENABLED=1`

---------

方法二选一

**Comment by yangxu52** [comment]
> > > > > 解决方法：[xiaorouji/openwrt-passwall#2969](https://github.com/xiaorouji/openwrt-passwall/discussions/2969)
> > > > 
> > > > 
> > > > 如果同时编译sing-box和xray-core，是否有更优解？ 目前sing-box在golang 1.21.x能编译通过，xray-core 1.8.7在golang 1.21.x也能通过，但是xray-core 1.8.8需要golang 1.22.x
> > > 
> > > 
> > > go1.22 可以编译xray-* 和 sing-box。甚至可以编译 go1.21 能编译的所有包
> > > 这里是用 go1.22 编译出来的包：https://opkg.cooluc.com/openwrt-23.05/aarch64_generic/
> > > 我使用github action编译的固件，看到xray-core升级后，我将golang替换到了1.22.x ![image](https://private-user-images.githubusercontent.com/64672399/308083879-58326668-1cb4-42a8-824e-8f5b8e24cdf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjEyODgsIm5iZiI6MTcwOTAyMDk4OCwicGF0aCI6Ii82NDY3MjM5OS8zMDgwODM4NzktNTgzMjY2NjgtMWNiNC00MmE4LTgyNGUtOGY1YjhlMjRjZGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA4MDMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZDRiOGY0ODNmNDAzZjdiNTk1NzM1OWU4NGRlOTYzZDIzNGE1ZDFmY2FjYTgxYzc2NzZiMGJmYzc2ZGY1NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hzNNekUUJ8qzWE8baVjjB7xVNj1acp_dZQ2Kk5jj-IA) 之前sing-box是能编译过的。
> 
> 是这里的 singbox 包问题，go1.22 要求 cgo。根据：[golang/go@079dfdc](https://github.com/golang/go/commit/079dfdcac0448168e22a72baa61b9ab5de8ce54e)
> 
> 解决方法两个： 1、使用这个 singbox 包 https://github.com/sbwml/openwrt_helloworld/tree/v5/sing-box
> 
> 2、直接删除 https://github.com/xiaorouji/openwrt-passwall-packages/blob/main/sing-box/Makefile#L49 这行，或者把 `CGO_ENABLED=0` 改成 ` CGO_ENABLED=1`
> 
> 方法二选一

没怎么接触过golang，它的版本兼容性不太理解，前面理解有问题。
我已经修改了编译脚本，我再试试。
感谢！
