### ISSUE TITLE
 [Bug]: 每次编译passwall都报这个错误

### ISSUE THREAD

**Issue by Glunefish** [xiaorouji/openwrt-passwall-packages#151]
### 描述您遇到的bug

time: package/feeds/packages/libffi/host-compile#0.13#0.05#0.18
make[3]: Entering directory '/workdir/openwrt/package/utils/bzip2'
mkdir -p /workdir/openwrt/dl
SHELL= flock /workdir/openwrt/tmp/.bzip2-1.0.8.tar.gz.flock -c '  [ -f "/workdir/openwrt/dl/bzip2-1.0.8.tar.gz" ] || ( 	/workdir/openwrt/scripts/download.pl "/workdir/openwrt/dl" "bzip2-1.0.8.tar.gz" "ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269" "" "https://sourceware.org/pub/bzip2"     )'
make[3]: Leaving directory '/workdir/openwrt/package/utils/bzip2'
time: package/utils/bzip2/host-compile#0.14#0.05#0.17
make[3]: Entering directory '/workdir/openwrt/feeds/packages/lang/python/python3'
mkdir -p /workdir/openwrt/dl
SHELL= flock /workdir/openwrt/tmp/.Python-3.10.5.tar.xz.flock -c '  [ -f "/workdir/openwrt/dl/Python-3.10.5.tar.xz" ] || ( 	/workdir/openwrt/scripts/download.pl "/workdir/openwrt/dl" "Python-3.10.5.tar.xz" "8437efd5b106ef0a75aabfbf23d880625120a73a86a22ade4d2e2e68d7b74486" "" "https://www.python.org/ftp/python/3.10.5"     )'
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/lang/python/python3'
time: package/feeds/packages/python3/host-compile#0.17#0.10#0.24
make[3]: Entering directory '/workdir/openwrt/feeds/packages/lang/rust'
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/lang/rust'
time: package/feeds/packages/rust/host-compile#0.67#1.94#4.61
make[3]: Entering directory '/workdir/openwrt/feeds/passwall_packages/shadowsocks-rust'
mkdir -p /workdir/openwrt/dl
SHELL= flock /workdir/openwrt/tmp/.shadowsocks-rust-1.18.1.tar.gz.flock -c '  [ -f "/workdir/openwrt/dl/shadowsocks-rust-1.18.1.tar.gz" ] || ( 	/workdir/openwrt/scripts/download.pl "/workdir/openwrt/dl" "shadowsocks-rust-1.18.1.tar.gz" "c2e1d8838e4578c0a6b0de6e1da00e9ece2d780dc452117fd109bb091e5d106f" "" "https://codeload.github.com/shadowsocks/shadowsocks-rust/tar.gz/v1.18.1?"     )'
rm -f /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocks-rust-1.18.1/.built
touch /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocks-rust-1.18.1/.built_check
CFLAGS="-Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include -I/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/include -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/include/fortify -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/include " CXXFLAGS="-Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include -I/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/include -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/include/fortify -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/include " LDFLAGS="-L/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/lib -L/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/lib -L/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/lib -znow -zrelro " make  -C /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocks-rust-1.18.1/. AR="aarch64-openwrt-linux-musl-gcc-ar" AS="ccache_cc -c -Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=aarch64-openwrt-linux-musl-ld NM="aarch64-openwrt-linux-musl-gcc-nm" CC="ccache_cc" GCC="ccache_cc" CXX="ccache_cxx" RANLIB="aarch64-openwrt-linux-musl-gcc-ranlib" STRIP=aarch64-openwrt-linux-musl-strip OBJCOPY=aarch64-openwrt-linux-musl-objcopy OBJDUMP=aarch64-openwrt-linux-musl-objdump SIZE=aarch64-openwrt-linux-musl-size CROSS="aarch64-openwrt-linux-musl-" ARCH="aarch64" CARGO_HOME="/workdir/openwrt/staging_dir/host/cargo" ;
make[4]: Entering directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocks-rust-1.18.1'
cargo build --features "local-tun local-redir"
error: package `shadowsocks v1.18.1 (/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocks-rust-1.18.1/crates/shadowsocks)` cannot be built because it requires rustc 1.71 or newer, while the currently active rustc version is 1.67.1

make[4]: *** [Makefile:11: build] Error 101
make[4]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocks-rust-1.18.1'
make[3]: *** [Makefile:55: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocks-rust-1.18.1/.built] Error 2
make[3]: Leaving directory '/workdir/openwrt/feeds/passwall_packages/shadowsocks-rust'
time: package/feeds/passwall_packages/shadowsocks-rust/compile#0.23#0.15#0.38
make[2]: *** [package/Makefile:113: package/feeds/passwall_packages/shadowsocks-rust/compile] Error 2
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:107: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:227: world] Error 2
Error: Process completed with exit code 2.

### 复现此Bug的步骤

https://github.com/Glunefish/OPBuild/actions/runs/8084631230/job/22090327093#step:15:9360

### 您想要实现的目的

编译passwall

### 日志信息

time: package/feeds/packages/libffi/host-compile#0.13#0.05#0.18
make[3]: Entering directory '/workdir/openwrt/package/utils/bzip2'
mkdir -p /workdir/openwrt/dl
SHELL= flock /workdir/openwrt/tmp/.bzip2-1.0.8.tar.gz.flock -c '  [ -f "/workdir/openwrt/dl/bzip2-1.0.8.tar.gz" ] || ( 	/workdir/openwrt/scripts/download.pl "/workdir/openwrt/dl" "bzip2-1.0.8.tar.gz" "ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269" "" "https://sourceware.org/pub/bzip2"     )'
make[3]: Leaving directory '/workdir/openwrt/package/utils/bzip2'
time: package/utils/bzip2/host-compile#0.14#0.05#0.17
make[3]: Entering directory '/workdir/openwrt/feeds/packages/lang/python/python3'
mkdir -p /workdir/openwrt/dl
SHELL= flock /workdir/openwrt/tmp/.Python-3.10.5.tar.xz.flock -c '  [ -f "/workdir/openwrt/dl/Python-3.10.5.tar.xz" ] || ( 	/workdir/openwrt/scripts/download.pl "/workdir/openwrt/dl" "Python-3.10.5.tar.xz" "8437efd5b106ef0a75aabfbf23d880625120a73a86a22ade4d2e2e68d7b74486" "" "https://www.python.org/ftp/python/3.10.5"     )'
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/lang/python/python3'
time: package/feeds/packages/python3/host-compile#0.17#0.10#0.24
make[3]: Entering directory '/workdir/openwrt/feeds/packages/lang/rust'
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/lang/rust'
time: package/feeds/packages/rust/host-compile#0.67#1.94#4.61
make[3]: Entering directory '/workdir/openwrt/feeds/passwall_packages/shadowsocks-rust'
mkdir -p /workdir/openwrt/dl
SHELL= flock /workdir/openwrt/tmp/.shadowsocks-rust-1.18.1.tar.gz.flock -c '  [ -f "/workdir/openwrt/dl/shadowsocks-rust-1.18.1.tar.gz" ] || ( 	/workdir/openwrt/scripts/download.pl "/workdir/openwrt/dl" "shadowsocks-rust-1.18.1.tar.gz" "c2e1d8838e4578c0a6b0de6e1da00e9ece2d780dc452117fd109bb091e5d106f" "" "https://codeload.github.com/shadowsocks/shadowsocks-rust/tar.gz/v1.18.1?"     )'
rm -f /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocks-rust-1.18.1/.built
touch /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocks-rust-1.18.1/.built_check
CFLAGS="-Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include -I/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/include -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/include/fortify -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/include " CXXFLAGS="-Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro  -I/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/include -I/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/include -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/include/fortify -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/include " LDFLAGS="-L/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/lib -L/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/lib -L/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-7.5.0_musl/lib -znow -zrelro " make  -C /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocks-rust-1.18.1/. AR="aarch64-openwrt-linux-musl-gcc-ar" AS="ccache_cc -c -Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=aarch64-openwrt-linux-musl-ld NM="aarch64-openwrt-linux-musl-gcc-nm" CC="ccache_cc" GCC="ccache_cc" CXX="ccache_cxx" RANLIB="aarch64-openwrt-linux-musl-gcc-ranlib" STRIP=aarch64-openwrt-linux-musl-strip OBJCOPY=aarch64-openwrt-linux-musl-objcopy OBJDUMP=aarch64-openwrt-linux-musl-objdump SIZE=aarch64-openwrt-linux-musl-size CROSS="aarch64-openwrt-linux-musl-" ARCH="aarch64" CARGO_HOME="/workdir/openwrt/staging_dir/host/cargo" ;
make[4]: Entering directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocks-rust-1.18.1'
cargo build --features "local-tun local-redir"
error: package `shadowsocks v1.18.1 (/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocks-rust-1.18.1/crates/shadowsocks)` cannot be built because it requires rustc 1.71 or newer, while the currently active rustc version is 1.67.1

make[4]: *** [Makefile:11: build] Error 101
make[4]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocks-rust-1.18.1'
make[3]: *** [Makefile:55: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shadowsocks-rust-1.18.1/.built] Error 2
make[3]: Leaving directory '/workdir/openwrt/feeds/passwall_packages/shadowsocks-rust'
time: package/feeds/passwall_packages/shadowsocks-rust/compile#0.23#0.15#0.38
make[2]: *** [package/Makefile:113: package/feeds/passwall_packages/shadowsocks-rust/compile] Error 2
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:107: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:227: world] Error 2
Error: Process completed with exit code 2.

### 系统相关信息

src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main
src-git passwall_luci https://github.com/xiaorouji/openwrt-passwall.git;main

**Comment by smallprogram** [comment]
it requires rustc 1.71 or newer, while the currently active rustc version is 1.67.1

**Comment by Glunefish** [comment]
> it requires rustc 1.71 or newer, while the currently active rustc version is 1.67.1它需要 Rustc 1.71 或更高版本，而当前活跃的 Rustc 版本是 1.67.1

我知道它需要这个新版本，就是编译文件也是写的1.8的新版但是它不编译1.8

**Comment by smallprogram** [comment]
> > it requires rustc 1.71 or newer, while the currently active rustc version is 1.67.1它需要 Rustc 1.71 或更高版本，而当前活跃的 Rustc 版本是 1.67.1
> 
> 我知道它需要这个新版本，就是编译文件也是写的1.8的新版但是它不编译1.8

嗯，是这样的，shadowsocks v1.18.1的makefile中写到
https://github.com/xiaorouji/openwrt-passwall-packages/blob/2b6271767a5368fc559487e739d9f63354a98de7/shadowsocks-rust/Makefile#L20-L21
这里表示shadowsocks 编译依赖于rust，在你编译的过程中报错
`it requires rustc 1.71 or newer, while the currently active rustc version is 1.67.1它需要 Rustc 1.71 或更高版本，而当前活跃的 Rustc 版本是 1.67.1`
表明你的openwrt packages feeds中的rust的版本是1.67.1，但是编译依赖的rust必须是1.71或更高
所以你需要修正你的package feed中的rust版本，目前openwrt官方packages的rust版本为1.76.0，lean的packages源码rust版本为1.74.1，理论上满足SS的编译要求。但是由于我不知道你用的谁的op源码，也不知道你所用的op源码中是否存在某些rust的patch,所以无法继续提供相关的解决方案。

**Comment by Glunefish** [comment]
非常感谢你的帮助！我使用的是sdf8057的源码，可能因为作者没有维护的原因导致源码版本较低，我会试着修改一下rust或升级一下版本尝试，两次感谢你的解答，因为我不是很懂这方面，目前也是学习编译，谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月29日(周四) 中午1:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaorouji/openwrt-passwall-packages]  [Bug]: 每次编译passwall都报这个错误 (Issue #151)




   
it requires rustc 1.71 or newer, while the currently active rustc version is 1.67.1它需要 Rustc 1.71 或更高版本，而当前活跃的 Rustc 版本是 1.67.1
  
我知道它需要这个新版本，就是编译文件也是写的1.8的新版但是它不编译1.8
  
嗯，是这样的，shadowsocks v1.18.1的makefile中写到
 https://github.com/xiaorouji/openwrt-passwall-packages/blob/2b6271767a5368fc559487e739d9f63354a98de7/shadowsocks-rust/Makefile#L20-L21
 这里表示shadowsocks 编译依赖于rust，在你编译的过程中报错
 it requires rustc 1.71 or newer, while the currently active rustc version is 1.67.1它需要 Rustc 1.71 或更高版本，而当前活跃的 Rustc 版本是 1.67.1
 表明你的openwrt packages feeds中的rust的版本是1.67.1，但是编译依赖的rust必须是1.71或更高
 所以你需要修正你的package feed中的rust版本，目前openwrt官方packages的rust版本为1.76.0，lean的packages源码rust版本为1.74.1，理论上满足SS的编译要求。但是由于我不知道你用的谁的op源码，也不知道你所用的op源码中是否存在某些rust的patch,所以无法继续提供相关的解决方案。

**Comment by Glunefish** [comment]
你好，我想问一下能否从云编译的脚本中进行升级，要写什么代码，能否教我一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月29日(周四) 中午1:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaorouji/openwrt-passwall-packages]  [Bug]: 每次编译passwall都报这个错误 (Issue #151)




   
it requires rustc 1.71 or newer, while the currently active rustc version is 1.67.1它需要 Rustc 1.71 或更高版本，而当前活跃的 Rustc 版本是 1.67.1
  
我知道它需要这个新版本，就是编译文件也是写的1.8的新版但是它不编译1.8
  
嗯，是这样的，shadowsocks v1.18.1的makefile中写到
 https://github.com/xiaorouji/openwrt-passwall-packages/blob/2b6271767a5368fc559487e739d9f63354a98de7/shadowsocks-rust/Makefile#L20-L21
 这里表示shadowsocks 编译依赖于rust，在你编译的过程中报错
 it requires rustc 1.71 or newer, while the currently active rustc version is 1.67.1它需要 Rustc 1.71 或更高版本，而当前活跃的 Rustc 版本是 1.67.1
 表明你的openwrt packages feeds中的rust的版本是1.67.1，但是编译依赖的rust必须是1.71或更高
 所以你需要修正你的package feed中的rust版本，目前openwrt官方packages的rust版本为1.76.0，lean的packages源码rust版本为1.74.1，理论上满足SS的编译要求。但是由于我不知道你用的谁的op源码，也不知道你所用的op源码中是否存在某些rust的patch,所以无法继续提供相关的解决方案。

**Comment by smallprogram** [comment]
@Glunefish 最根本的解决方案是，更新的op源码中rust的makefile及相关文件，你可以尝试将op官方的rust代码或者lean的rust替换掉你当前rust代码。进而尝试一下。再或者，放弃使用sdf8057源码。再或者，用其他人编译好的固件，比如我的一个op云编译版本固件，[推销一下😊]，https://github.com/smallprogram/OpenWrtAction，支持x86，arm等平台。使用lean的源码，集成多种插件。

**Comment by Glunefish** [comment]
大佬，你的源码支持zn-m2吗&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月29日(周四) 下午2:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaorouji/openwrt-passwall-packages]  [Bug]: 每次编译passwall都报这个错误 (Issue #151)




 
@Glunefish 最根本的解决方案是，更新的op源码中rust的makefile及相关文件，你可以尝试将op官方的rust代码或者lean的rust替换掉你当前rust代码。进而尝试一下。再或者，放弃使用sdf8057源码。再或者，用其他人编译好的固件，比如我的一个op云编译版本固件，[推销一下😊]，https://github.com/smallprogram/OpenWrtAction ，支持x86，arm等平台。使用lean的源码，集成多种插件。

**Comment by smallprogram** [comment]
@Glunefish zn-m2是啥？

**Comment by Glunefish** [comment]
ipq6000 zn m2路由器



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月1日(周五) 凌晨1:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaorouji/openwrt-passwall-packages]  [Bug]: 每次编译passwall都报这个错误 (Issue #151)




 
@Glunefish zn-m2是啥？

**Comment by smallprogram** [comment]
奥，看了一下，是个硬路由，内存也不大，wifi驱动估计很难搞

**Comment by Glunefish** [comment]
有搞好了的文件，就是我不会移植，然后其实也不需要无线



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月1日(周五) 凌晨1:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaorouji/openwrt-passwall-packages]  [Bug]: 每次编译passwall都报这个错误 (Issue #151)




 
奥，看了一下，是个硬路由，内存也不大，wifi驱动估计很难搞

**Comment by Glunefish** [comment]
sdf8057大佬的ipq6000源码



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月1日(周五) 凌晨1:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaorouji/openwrt-passwall-packages]  [Bug]: 每次编译passwall都报这个错误 (Issue #151)




 
奥，看了一下，是个硬路由，内存也不大，wifi驱动估计很难搞
