### ISSUE TITLE
[Bug]: v2ray-core & v2ray-plugin 5.14.1 编译需要Go 1.2.2支持 

### ISSUE THREAD

**Issue by bi4tms** [xiaorouji/openwrt-passwall-packages#157]
### 描述您遇到的bug

编译最新组件需要go 1.2.2支持

### 复现此Bug的步骤

拉取最新源码编译

### 您想要实现的目的

修复bug

### 日志信息

同上

### 系统相关信息

同上

**Comment by smallprogram** [comment]
https://github.com/xiaorouji/openwrt-passwall-packages/issues/146
