### ISSUE TITLE
[Bug]: lean源码编译到v2ray-plugin报错，取消勾选也不行 。

### ISSUE THREAD

**Issue by chris7395328** [xiaorouji/openwrt-passwall-packages#169]
### 描述您遇到的bug

 lean源码编译360v6，到v2ray-plugin报错，取消勾选也不行，只保留singbox和xray，还是会卡在这里

### 复现此Bug的步骤

云编译，config 中passwall只选择了singbox和xray

### 您想要实现的目的

编译固件

### 日志信息

make[3]: Entering directory '/workdir/openwrt/feeds/passwallpackages/v2ray-plugin'
rm -f /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/v2ray-plugin-5.14.1/.built
touch /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/v2ray-plugin-5.14.1/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/workdir/openwrt/tmp/go-build" GO_MOD_CACHE_DIR="/workdir/openwrt/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/shadowsocks/v2ray-plugin" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/shadowsocks/v2ray-plugin/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/v2ray-plugin-5.14.1" GO_BUILD_DIR="/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/v2ray-plugin-5.14.1/.go_work/build" GO_BUILD_BIN_DIR="/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/v2ray-plugin-5.14.1/.go_work/build/bin/linux_arm64" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/usr/share/gocode/src" GOOS="linux" GOARCH="arm64" GO386="" GOAMD64="" GOARM="" GOMIPS="" GOMIPS64="" GOPPC64="" CGO_ENABLED=1 CC="aarch64-openwrt-linux-musl-gcc" CXX="aarch64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/v2ray-plugin-5.14.1=v2ray-plugin-5.14.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/include/fortify -I/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/include" CGO_CXXFLAGS="-Os -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/v2ray-plugin-5.14.1=v2ray-plugin-5.14.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/lib -znow -zrelro" GOPATH="/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/v2ray-plugin-5.14.1/.go_work/build" GOCACHE="/workdir/openwrt/tmp/go-build" GOMODCACHE="/workdir/openwrt/dl/go-mod-cache" GOENV=off GOTOOLCHAIN=local /usr/bin/env bash /workdir/openwrt/feeds/packages/lang/golang//golang-build.sh build -v -buildvcs=false -trimpath -ldflags "all=-buildid '1686251287' -linkmode external -extldflags '-L/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"        -ldflags " -X main.VERSION=v5.14.1 -buildid '1686251287' -linkmode external -extldflags '-L/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-aarch64_cortex-a53_gcc-11.3.0_musl/lib -Wl,-z,now -Wl,-z,relro'"  
Finding targets
go: ../../go.mod requires go >= 1.22 (running go 1.21.5; GOTOOLCHAIN=local)

Building targets
go: ../../go.mod requires go >= 1.22 (running go 1.21.5; GOTOOLCHAIN=local)

make[3]: *** [Makefile:44: /workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/v2ray-plugin-5.14.1/.built] Error 1
make[3]: Leaving directory '/workdir/openwrt/feeds/passwallpackages/v2ray-plugin'
time: package/feeds/passwallpackages/v2ray-plugin/compile#0.14#0.07#0.19
    ERROR: package/feeds/passwallpackages/v2ray-plugin failed to build.
make[2]: *** [package/Makefile:116: package/feeds/passwallpackages/v2ray-plugin/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

### 系统相关信息

https://github.com/xiaorouji/openwrt-passwall

`CONFIG_PACKAGE_luci-app-passwall=y

CONFIG_PACKAGE_luci-app-passwall=y

#
# Configuration
#
CONFIG_PACKAGE_luci-app-passwall_Iptables_Transparent_Proxy=y
# CONFIG_PACKAGE_luci-app-passwall_Nftables_Transparent_Proxy is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Haproxy is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Hysteria is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_NaiveProxy is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Client is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Server is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Rust_Client is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Rust_Server is not set
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Client=y
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Server is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Simple_Obfs is not set
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_SingBox=y
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_tuic_client is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Geodata is not set
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Plugin is not set
CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Xray=y
# CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Xray_Plugin is not set
# end of Configuration`

**Comment by jmmes** [comment]
同样卡在这里，一直不成功！

**Comment by chris7395328** [comment]
> 同样卡在这里，一直不成功！

好吧查看了下是因为别的地方自动勾选了v2ray，全部叉掉就ok了，应该还是golang的版本问题。

**Comment by jmmes** [comment]
> > 同样卡在这里，一直不成功！
> 
> 好吧查看了下是因为别的地方自动勾选了v2ray，全部叉掉就ok了，应该还是golang的版本问题。

我升级golang了，还是报错，叉掉等于没有插件了

**Comment by chris7395328** [comment]
> > > 同样卡在这里，一直不成功！
> > 
> > 
> > 好吧查看了下是因为别的地方自动勾选了v2ray，全部叉掉就ok了，应该还是golang的版本问题。
> 
> 我升级golang了，还是报错，叉掉等于没有插件了

你passwall的插件就选一个singbox，别的用大雕的ssr的插件就行了，勾ssr的xray，passwall这边就不要勾xray和v2ray这些。
