### ISSUE TITLE
[Bug]: shadowsocks-rust 在 22.03.6上编译失败

### ISSUE THREAD

**Issue by 0x01-0xff** [xiaorouji/openwrt-passwall-packages#186]
### 描述您遇到的bug

官源22.03.6编译，在 feed update -a 阶段就提示错误，导致后面编译失败，在23.05.3下是没问题的
`Collecting package info: feeds/passwall_pkg/brook
Collecting package info: feeds/passwall_pkg/chinadns-ng
Collecting package info: feeds/passwall_pkg/dns2socks
Collecting package info: feeds/passwall_pkg/dns2tcp
Collecting package info: feeds/passwall_pkg/gn
Collecting package info: feeds/passwall_pkg/hysteria
Collecting package info: feeds/passwall_pkg/ipt2socks
Collecting package info: feeds/passwall_pkg/microsocks
Collecting package info: feeds/passwall_pkg/naiveproxy
Collecting package info: feeds/passwall_pkg/pdnsd-alt
Collecting package info: feeds/passwall_pkg/shadowsocks-rust
ERROR: please fix feeds/passwall_pkg/shadowsocks-rust/Makefile - see logs/feeds/passwall_pkg/shadowsocks-rust/dump.txt for details`
最后编译失败
`WARNING: Makefile 'package/feeds/passwall_pkg/shadowsocks-rust/Makefile' has a build dependency on 'rust/host', which does not exist`
`ERROR: package/feeds/passwall_pkg/shadowsocks-rust failed to build.`

### 复现此Bug的步骤

无

### 您想要实现的目的

正常编译

### 日志信息

`Collecting package info: feeds/passwall_pkg/brook
Collecting package info: feeds/passwall_pkg/chinadns-ng
Collecting package info: feeds/passwall_pkg/dns2socks
Collecting package info: feeds/passwall_pkg/dns2tcp
Collecting package info: feeds/passwall_pkg/gn
Collecting package info: feeds/passwall_pkg/hysteria
Collecting package info: feeds/passwall_pkg/ipt2socks
Collecting package info: feeds/passwall_pkg/microsocks
Collecting package info: feeds/passwall_pkg/naiveproxy
Collecting package info: feeds/passwall_pkg/pdnsd-alt
Collecting package info: feeds/passwall_pkg/shadowsocks-rust
ERROR: please fix feeds/passwall_pkg/shadowsocks-rust/Makefile - see logs/feeds/passwall_pkg/shadowsocks-rust/dump.txt for details`

### 截图

![1671711536412_ pic](https://github.com/xiaorouji/openwrt-passwall-packages/assets/18429669/b4aae636-a2f9-4712-ba08-228b646b1463)

### 系统相关信息

无

**Comment by lwb1978** [comment]
ss编译失败应该到ss那边反馈，这边只有一个makefile而已。或者采用二进制方式，具体参考这个仓库：https://github.com/sbwml/openwrt_helloworld

**Comment by sbwml** [comment]
> ss编译失败应该到ss那边反馈，这边只有一个makefile而已。或者采用二进制方式，具体参考这个仓库：https://github.com/sbwml/openwrt_helloworld

🤡 楼上失败是预期行为，因为 `package/lang/rust` 自 23.05-SNAPSHOT 起开始提供。先不说楼上为什么会编译失败，可能连 PR 的人都不知道他自己在做什么 #115 😆

**Comment by lwb1978** [comment]
> > ss编译失败应该到ss那边反馈，这边只有一个makefile而已。或者采用二进制方式，具体参考这个仓库：https://github.com/sbwml/openwrt_helloworld
> 
> 🤡 楼上失败是预期行为，因为 `package/lang/rust` 自 23.05-SNAPSHOT 起开始提供。先不说楼上为什么会编译失败，可能连 PR 的人都不知道他自己在做什么 #115 😆
> 
> 这并不是仅仅一个 makefile 的事情，而是已经一棍子打死 openwrt 23 以下的所有版本正常构建

我本来也想把你的库提交个PR到这来，后来看了下shadowsocks-rust不提供mips/mipsel的二进制，得重新建库编译，又不好在passwall的官方库中引用你shadowsocks-rust-mips的库，怕大佬说不严谨。所以我现在干脆直接使用你的核心库了，其他反馈类似问题的我看到了也推荐他们用你的库。

**Comment by 0x01-0xff** [comment]
感谢楼上两位大佬。从https://git.openwrt.org/feed/packages.git拉取rust文件夹放到相应位置依然失败，只是没有rust/host的错误提示了，还有个pcre2/host警告。现尝试用楼上大佬的库。

**Comment by lwb1978** [comment]
> 感谢楼上两位大佬。从[https://git.openwrt.org/feed/packages.git拉取rust文件夹放到相应位置依然失败，只是没有rust/host的错误提示了，还有个pcre2/host警告。现尝试用楼上大佬的库。](https://git.openwrt.org/feed/packages.git%E6%8B%89%E5%8F%96rust%E6%96%87%E4%BB%B6%E5%A4%B9%E6%94%BE%E5%88%B0%E7%9B%B8%E5%BA%94%E4%BD%8D%E7%BD%AE%E4%BE%9D%E7%84%B6%E5%A4%B1%E8%B4%A5%EF%BC%8C%E5%8F%AA%E6%98%AF%E6%B2%A1%E6%9C%89rust/host%E7%9A%84%E9%94%99%E8%AF%AF%E6%8F%90%E7%A4%BA%E4%BA%86%EF%BC%8C%E8%BF%98%E6%9C%89%E4%B8%AApcre2/host%E8%AD%A6%E5%91%8A%E3%80%82%E7%8E%B0%E5%B0%9D%E8%AF%95%E7%94%A8%E6%A5%BC%E4%B8%8A%E5%A4%A7%E4%BD%AC%E7%9A%84%E5%BA%93%E3%80%82)

@sbwml 大佬的库基本能用二进制文件的都采用二进制文件的方式，所以编译速度快不少，用了就回不去了，希望能长期维护下去。😆
