### ISSUE TITLE
[Bug]: ChinaDNS-NG 20240413版更新后，DNS不正常工作。

### ISSUE THREAD

**Issue by iamyangyiok** [xiaorouji/openwrt-passwall-packages#199]
### 描述您遇到的bug

ChinaDNS-NG 20240413版更新后，勾上过滤代理域名 IPv6，DNS不正常工作。关闭了就正常。
PW 4.76-4 
CHINADNS-DNS 20240413

### 复现此Bug的步骤

ChinaDNS-NG 20240413版更新后，DNS不正常工作。关闭了就正常。

### 您想要实现的目的

修复

### 日志信息

PW 4.76-4 
CHINADNS-DNS 20240413

### 系统相关信息

PW 4.76-4 
CHINADNS-DNS 20240413

**Comment by lwb1978** [comment]
请更新到4.76-5版passwall
