### ISSUE TITLE
[Bug]: 编译报错

### ISSUE THREAD

**Issue by Kuron88** [xiaorouji/openwrt-passwall-packages#225]
### 描述您遇到的bug

编译过程，只要到这个位置就报错了

### 复现此Bug的步骤

无

### 您想要实现的目的

解决能正常编译

### 日志信息

{standard input}: Assembler messages:
{standard input}:4260: Error: opcode not supported on this processor: mips2 (mips2) sync' {standard input}:4535: Error: opcode not supported on this processor: mips2 (mips2) sync'
make[4]: *** [Makefile:25: libev/ev.o] Error 1
make[4]: Leaving directory '/home/kuron/lede/build_dir/target-mipsel_24kc_musl/dns2tcp-1.1.1'
make[3]: *** [Makefile:45: /home/kuron/lede/build_dir/target-mipsel_24kc_musl/dns2tcp-1.1.1/.built] Error 2
make[3]: Leaving directory '/home/kuron/lede/feeds/passwall/dns2tcp'
time: package/feeds/passwall/dns2tcp/compile#0.40#0.12#0.52
ERROR: package/feeds/passwall/dns2tcp failed to build.
make[2]: *** [package/Makefile:116: package/feeds/passwall/dns2tcp/compile] Error 1
make[2]: Leaving directory '/home/kuron/lede'
make[1]: *** [package/Makefile:110: /home/kuron/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/kuron/lede'
make: *** [/home/kuron/lede/include/toplevel.mk:231：world] 错误 2

### 系统相关信息

passwall477-5

**Comment by Kuron88** [comment]
dns2tcp这个依赖的问题，我把这个退到1.1.0的版本就可以了

**Comment by lxhao61** [comment]
> dns2tcp这个依赖的问题，我把这个退到1.1.0的版本就可以了

回退虽然可以解决当前问题，但无法同步更新了。
