### ISSUE TITLE
[Bug]: newifi d1 编译出错，cpu是mt7621

### ISSUE THREAD

**Issue by eearphon** [xiaorouji/openwrt-passwall-packages#231]
### 描述您遇到的bug

dns2tcp最后一次升级后就编译出错，之前正常

### 复现此Bug的步骤

编译错误

### 您想要实现的目的

正常编译

### 日志信息

make[4]: Entering directory '/workdir/openwrt/build_dir/target-mipsel_24kc_musl/dns2tcp-1.1.1'
mipsel-openwrt-linux-musl-gcc -std=c99 -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -mips16 -minterlink-mips16 -fmacro-prefix-map=/workdir/openwrt/build_dir/target-mipsel_24kc_musl/dns2tcp-1.1.1=dns2tcp-1.1.1 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -DPIC -fpic -c libev/ev.c -o libev/ev.o
libev/ev.c:2139:31: warning: 'ev_default_loop_ptr' initialized and declared 'extern'
EV_API_DECL struct ev_loop ev_default_loop_ptr = 0; / needs to be initialised to make it a definition despite extern */
^~~~~~~~~~~~~~~~~~~
{standard input}: Assembler messages:
{standard input}:4260: Error: opcode not supported on this processor: mips2 (mips2) sync' {standard input}:4535: Error: opcode not supported on this processor: mips2 (mips2) sync'
make[4]: *** [Makefile:25: libev/ev.o] Error 1
make[4]: Leaving directory '/workdir/openwrt/build_dir/target-mipsel_24kc_musl/dns2tcp-1.1.1'
make[3]: *** [Makefile:45: /workdir/openwrt/build_dir/target-mipsel_24kc_musl/dns2tcp-1.1.1/.built] Error 2
make[3]: Leaving directory '/workdir/openwrt/feeds/small/dns2tcp'
time: package/feeds/small/dns2tcp/compile#0.36#0.08#0.42
ERROR: package/feeds/small/dns2tcp failed to build.
make[2]: *** [package/Makefile:116: package/feeds/small/dns2tcp/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

### 系统相关信息

最新版passwall

**Comment by lxhao61** [comment]
一样，OpenWrt 22.03 都这样。

**Comment by qingtian110** [comment]
更换成这个包就正常了    https://github.com/sbwml/openwrt_helloworld/tree/v5/dns2tcp

**Comment by lxhao61** [comment]
> 更换成这个包就正常了 https://github.com/sbwml/openwrt_helloworld/tree/v5/dns2tcp

使用你提供方法解决了问题。谢谢！
希望此项目可以参考上述链接解决问题。

**Comment by eearphon** [comment]
隔壁的方法是加回这一行 PKG_USE_MIPS16:=0
