### ISSUE TITLE
hysteria v2.4.5 编译出错

### ISSUE THREAD

**Issue by lxhao61** [xiaorouji/openwrt-passwall-packages#233]
### 描述您遇到的bug

刚更新的 hysteria v2.4.5 编译出错，不能成功编译。

### 复现此Bug的步骤

无法编译成功。

### 您想要实现的目的

编译 hysteria v2.4.5。

### 日志信息

OpenWrt 22.03 编译出错日志链接：https://github.com/lxhao61/Actions-Original-OpenWrt/actions/runs/9380813952/job/25828658114

OpenWrt 23.05 编译出错日志链接： https://github.com/lxhao61/Actions-Original-OpenWrt/actions/runs/9380794869/job/25828596845

### 系统相关信息

Passwall 版本【 4.77-6 】

**Comment by Rhystar** [comment]
同样的报错

**Comment by sbwml** [comment]
仅供参考：https://github.com/sbwml/openwrt_helloworld/commit/17c7b0b98b3c8bc19eb71978f8371a3f93b9103a

**Comment by swxk521** [comment]
> 仅供参考：[sbwml/openwrt_helloworld@17c7b0b](https://github.com/sbwml/openwrt_helloworld/commit/17c7b0b98b3c8bc19eb71978f8371a3f93b9103a)

大佬，别参考了，直接PR吧

**Comment by sbwml** [comment]
PR 是一件过程非常复杂且没有必要的事情。这种操作理应由仓库所有者直接编辑文件来完成。

从 Windows 版邮件发送

发件人: 守望
发送时间: 2024年6月5日 19:52
收件人: xiaorouji/openwrt-passwall-packages
抄送: Bard; Comment
主题: Re: [xiaorouji/openwrt-passwall-packages] hysteria v2.4.5 编译出错 (Issue #233)

***@***.***
大佬，别参考了，直接PR吧
