### ISSUE TITLE
[Feature Request]: chinadns-ng 有提供支持 DoT + 硬件加速 的版本，是否有必要切换到这个版本？

### ISSUE THREAD

**Issue by qingtian110** [xiaorouji/openwrt-passwall-packages#240]
### 描述你想要的新功能

chinadns-ng 在passwall 是一种什么样子的存在？它是否有接管 DNS 上游解析操作？如果有更换带 wolfssl 的版本会不会好一些呀  大佬们

![image](https://github.com/xiaorouji/openwrt-passwall-packages/assets/87856890/7303ca16-149f-4daf-be2a-4db90fbed0fe)

### 描述你想要的解决方案

略

**Comment by sbwml** [comment]
觉得可以、但不是钢需，**硬件加速指令的版本**它只是针对 aarch64 & x86 架构构建 wolfssl 依赖时启用了AES-NI，在使用 tls 加密的 DNS 时可能会有略微提升，可是 DNS 解析这么轻量的数据，有没有硬件加速理论上是没有任何区别的（刻意进行基准测试除外）

换个说法则是，带 wolfssl 和不带 wolfssl 版本的区别仅仅是让 chinadns-ng 支持或不支持 DoT 协议的 DNS

**Comment by sbwml** [comment]
参考 https://github.com/sbwml/openwrt_helloworld/commit/3e8d165b4d0a94352009735e5b851a52ad24fb08

**Comment by lwb1978** [comment]
其实我觉得没什么必要，目前chinadns-ng 在passwall中的位置用不到DOT

**Comment by lwb1978** [comment]
@sbwml 官方那边新提供了mips64和mips64el架构的二进制文件，能否跟进一下makefile，谢谢。

**Comment by sbwml** [comment]
> @sbwml 官方那边新提供了mips64和mips64el架构的二进制文件，能否跟进一下makefile，谢谢。

https://github.com/sbwml/openwrt_helloworld/commit/906d00116958dc425cc9abac5de03cd1e9fad7c0

OpenWrt 没有 `mips64el` 这种东西
