### ISSUE TITLE
[Feature Request]: deanonimization problem

### ISSUE THREAD

**Issue by vm-project-repo** [xiaorouji/openwrt-passwall-packages#264]
### 描述你想要的新功能

Some tips
[ Problem ]: I use PassWall and if any low level haker send authentification attack for my router he can see my real IP because previosly star work primary rom, next start internet connection and next start PassWall... 
[ Solving ]: if you add KILL SWITCH functionality it will be more secure if internet connection will be start after all soft on my device is loaded, same functionality have any GL.iNet devices, but  GL.iNet not secure and GL.iNet router hardware not secure, i mean:

Could you pls FIX IT: openwrt start -> internet connection start -> passwall start

How it should work: openwrt start ->  passwall start -> internet connection start

I mean that all soft/plugins or process should be loaded/start before internet connection will be start 

### 描述你想要的解决方案

I mean that all soft/plugins or process should be loaded/start before internet connection will be start 

### 描述你考虑过的替代方案

same functionality have any GL.iNet devices, but  GL.iNet not secure and GL.iNet router hardware not secure, i mean KILL SWITCH

**Comment by smallprogram** [comment]
Just modify the code in the 0_default_config file:
```
config global_delay
option auto_on '0'
option start_daemon '1'
option start_delay '60'
```
Modify the value of start_delay, the default is 60 seconds
