### ISSUE TITLE
[Bug]: sing-box编译失败

### ISSUE THREAD

**Issue by chenmozhijin** [xiaorouji/openwrt-passwall-packages#303]
### 描述您遇到的bug

58e817dce83258521a80d2f4099206e5ebef0521 中为sing-box添加了对kmod-nft-nat6的依赖,可官方源码中该包早已被删除https://github.com/openwrt/openwrt/commit/534e256c029bc47920d8b2544a43e568491b1af2

### 复现此Bug的步骤

在官方源码中编译sing-box

### 您想要实现的目的

解决依赖问题

### 日志信息

WARNING: Makefile 'package/cmzj_packages/openwrt-passwall-packages/sing-box/Makefile' has a dependency on 'kmod-nft-nat6', which does not exist

Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-nft-nat6 for sing-box
 * pkg_hash_fetch_best_installation_candidate: Packages for sing-box found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package sing-box.

### 系统相关信息

最新版本

**Comment by smallprogram** [comment]
![йокелеменеMenInBlackGIF](https://github.com/user-attachments/assets/d12872d5-5237-446a-9507-04bf4649d896)

**Comment by Gzxhwq** [comment]
改成kmod-nft-nat就可以了
