### ISSUE TITLE
[Bug]: sing-box.init里面iptables规则问题

### ISSUE THREAD

**Issue by canmengxian** [xiaorouji/openwrt-passwall-packages#50]
### 描述您遇到的bug

[  iptables -I FORWARD -o sb-tun+ -j ACCEPT](https://github.com/xiaorouji/openwrt-passwall-packages/blob/d38f54b58a8fffc4213fad6542d4baf76fe9f928/sing-box/files/sing-box.init#L39)，[  iptables -D FORWARD -o sb-tun+ -j ACCEPT](https://github.com/xiaorouji/openwrt-passwall-packages/blob/d38f54b58a8fffc4213fad6542d4baf76fe9f928/sing-box/files/sing-box.init#L45)，这条规则在NFtables下是用不了的，在最新passwall是否会用到，如果要用到的话如何修改。

### 复现此Bug的步骤

使用时打开防火墙发现的

### 您想要实现的目的

是否会用到，如果要用到的话如何修改。

### 日志信息

<img width="801" alt="image" src="https://github.com/xiaorouji/openwrt-passwall-packages/assets/37858783/cc48d515-394a-4cb9-940d-a01e7c057185">

### 系统相关信息

Passwall Version: 4.71-2

**Comment by Gzxhwq** [comment]
这个和passwall无关，也不影响使用，虽然说fw4用不了是真的
