### ISSUE TITLE
[Feature Request]: naiveproxy 更新119.0.6045.66-1

### ISSUE THREAD

**Issue by openips** [xiaorouji/openwrt-passwall-packages#55]
### 描述你想要的新功能

naiveproxy 已经更新到了 119.0.6045.66-1 tree里面的代码需要更新了

### 描述你想要的解决方案

更新naive到最新版本

**Comment by sdhz151** [comment]
这几天的passwall或passwall2。访问控制是无效的，你们看下是这样吗？
