### ISSUE TITLE
[Bug]: 新PACKAGES XRAY-CORE编译要求GOLANG 1.23

### ISSUE THREAD

**Issue by iamyangyiok** [xiaorouji/openwrt-passwall-packages#67]
### 描述您遇到的bug

编译报错：
Building targets
go: errors parsing go.mod:
/home/yai/immortalwrt-mt798x/build_dir/target-aarch64_cortex-a53_musl/Xray-core-1.8.6/go.mod:3: invalid go version '1.21.4': must match format 1.23

### 复现此Bug的步骤

1

### 日志信息

1

### 截图

1

### 系统相关信息

1

**Comment by iamyangyiok** [comment]
是不是BUG 没见GOLANG 1.23

**Comment by Gzxhwq** [comment]
openwrt/immortalwrt 21.02已经EOL了，Go版本停留在1.20，除非你自己编译前替换成Go 1.21.4
