### ISSUE TITLE
[Feature Request]: add xray-vless-TCP-XTLS

### ISSUE THREAD

**Issue by vm-project-repo** [xiaorouji/openwrt-passwall-packages#89]
### 描述你想要的新功能

Hello dear developer of PassWall,

My name Viktor and i'm Russian user of your PassWall. I mean that you soft more usefull than openclash and i every times setup PassWall on my router, but i have a problem within 2 last week. I can't visite to linkedin.com with xray-vless-TCP-REALTY.
And as you know users can't add xray-vless-TCP-XTLS with domain ssl from web UI of LuCI inteface (see printscrean)

### 描述你想要的解决方案

Could you pls add posibillity to add xray-vless-TCP-XTLS from LuCI inteface of openwrt routers.
This way open for many RU users access to linkedin.com 
I mean this will work because https encryptions with domain ssl (xray-vless-TCP-XTLS) better than xray-vless-TCP-REALTY

### 描述你考虑过的替代方案

I can slove the problem if i will be use openclash or if i will be use double vpn but openclash have not usefull and smart web interface as PassWall and double VPN - it is additional cost for second server and many manuals process for setupping

### 其他信息

Could you pls add to PassWall LuCI inteface chain with xray-vless-TCP-XTLS
![Screenshot 2023-12-22 at 00-47-34 OpenWrt - LuCI](https://github.com/xiaorouji/openwrt-passwall-packages/assets/49362988/18bf968a-4e81-4437-b7fb-03583ae8351d)

**Comment by Gzxhwq** [comment]
The old XTLS flow(direct, splice) has been deprecated by xray-core. There is only one XTLS flow vision now.

**Comment by Gzxhwq** [comment]
Sorry, I didn't use 3X-UI. 
But if you want to use xray-vless-TCP-XTLS, the screenshot what you post is xray-vless-TCP-XTLS. 
xray-vless-TCP-XTLS = "flow: rprx-rprx-vision" with "TLS" option ON.
