### ISSUE TITLE
[Bug]: passwall2依賴包少了好幾個

### ISSUE THREAD

**Issue by s920395** [xiaorouji/openwrt-passwall-packages#93]
### 描述您遇到的bug

![01](https://github.com/xiaorouji/openwrt-passwall-packages/assets/47146821/cccf247d-0e0f-4ccf-9631-97e85b422c84)
![02](https://github.com/xiaorouji/openwrt-passwall-packages/assets/47146821/63451b62-a73a-4e99-8f89-8139f7a17b91)
下載下來的依賴包和圖中比少了好幾個

### 复现此Bug的步骤

無

### 您想要实现的目的

想請您把依賴包補上

### 日志信息

無

### 系统相关信息

passwall2-1.22-1

**Comment by smallprogram** [comment]
你可以从make menuconfig中看到，ps2依赖包要比ps1少，这不是问题。我在action中列出的是packages中所有的依赖，其中包括了ps1和ps2的所有依赖。具体ps2的依赖可以参考makefile:
https://github.com/xiaorouji/openwrt-passwall2/blob/e4a3784c7ab17d3faf351855b672a57f0282e2e9/luci-app-passwall2/Makefile#L11-L28

**Comment by s920395** [comment]
所以ps2只安裝那16個依賴包就可以的意思，其他沒有放的依賴包沒安裝不會影響ps2使用是嗎?

**Comment by smallprogram** [comment]
> 所以ps2只安裝那16個依賴包就可以的意思，其他沒有放的依賴包沒安裝不會影響ps2使用是嗎?

可以这么理解，如果你不放心，可以自己单独编译一下ps2

**Comment by s920395** [comment]
感謝您解答我的疑惑，沒事了，謝謝您!
